### ISSUE TITLE
Greenkeeper badge is broken on README.md

### ISSUE THREAD

**Issue by dididy** [hyochan/react-native-switch-toggle#36]
I found greenkeeper badge is broken like below.
![](https://tva1.sinaimg.cn/large/006y8mN6gy1g88aonjau0j31fe05u3zq.jpg)

So I went into the link of badge image and the screen like this came out.
![](https://tva1.sinaimg.cn/large/006y8mN6gy1g88aobtm8mj30wg0bc0ua.jpg)

**Comment by hyochan** [comment]
@dididy 😆 Thank you for your kindness and reporting this issue. However, since this repository is no longer maintained. I'd want to ignore this one. Also, I hope you to checkout our recent library migrated into `react-hook`.

Have a look at [@dooboo-ui/native-switch-toggle](https://github.com/dooboolab/dooboo-ui-native/tree/master/src/components/shared/SwitchToggle).
