### ISSUE TITLE
Border Radius not working for circle

### ISSUE THREAD

**Issue by alexbowers** [hyochan/react-native-switch-toggle#4]
![image](https://user-images.githubusercontent.com/842974/43148691-bc0fd65e-8f5d-11e8-9c0d-88b5de692ce7.png)

![image](https://user-images.githubusercontent.com/842974/43148782-e84b3718-8f5d-11e8-9654-5fb72a6e6d42.png)

The border radius at the top is not there.

```
<SwitchToggle
  backgroundColorOn={'#fcc900'}
  backgroundColorOff={'transparent'}
  type={0}
  circleColorOn={'rgba(255, 255, 255, 1)'}
  circleColorOff={'rgba(255, 255, 255, 1)'}
  onPress={() => {
  console.log("Clicked");
  this.setState({marginValue: !this.state.marginValue});
  }}
  switchOn={this.state.marginValue}
/>
```

This is using the default styles for everything.

**Comment by alexbowers** [comment]
I just rolled back to `1.0.5` and it works as expected. A change in `1.0.6` must have caused this to break.

**Comment by dooboolab** [comment]
Sorry for late comeback. I've been missing this repo quite a while. This looks the breaks from [PR](https://github.com/react-native-seoul/react-native-switch-toggle/pull/3) cc @sajithneyo. 

Also, hope anyone can give us the `PR` for the fixes since I maybe busy working on other things these days. However, I'll always monitor for the `PR`. Thanks.

**Comment by hyochan** [comment]
Hi. `react-native-switch-toggle` has been deprecated for a while and is migrated to `react-hook` in [@dooboo-ui/native-switch-toggle](https://www.npmjs.com/package/@dooboo-ui/native-switch-toggle). Hope you guys to check this out.

**Comment by hyochan** [comment]
Closes due to inactivity. Version 2 is released just now. Please try it and come back @alexbowers .
